# Generated by Django 6.0.2 on 2026-02-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unspec', 'unspec')], default='unspec', max_length=6)),
                ('roll', models.CharField(default=20, max_length=4)),
                ('cls', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('new 10', 'new 10'), ('old 10', 'old 10')], max_length=7)),
                ('v_balance', models.IntegerField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Batch.batch')),
            ],
        ),
    ]
